### ISSUE TITLE
server start problems

### ISSUE THREAD

**Issue by chymian** [cgisky1980/ai00_rwkv_server#60]
I try to run the server on an debian 12 laptop with vulkan and a integrated GPU.

using the latest release, 0.3.11, I get the following error:

```024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ERROR [ai00_server] receiving on a closed channel
2024-01-06T19:11:43.640Z ^C
```
this error was introduced with 0.3.5.

going back to release 0.3.4, I get a diff. error:
even so, `Configs.toml` is there.
```
RUST_BACKTRACE=full ./ai00_server
2024-01-06T19:11:46.871Z INFO  [ai00_server] reading config assets/configs/Config.toml...
thread 'main' panicked at src/main.rs:585:49:
load frontend failed: No such file or directory (os error 2)
stack backtrace:
   0:     0x560fcffd84ff - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x560fcffd84ff - std::backtrace_rs::backtrace::trace_unsynchronized::h93125d0b85fd543c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560fcffd84ff - std::sys_common::backtrace::_print_fmt::h8d65f438e8343444
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560fcffd84ff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41751d2af6c8033a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x560fcfdded6c - core::fmt::rt::Argument::fmt::h5db2f552d8a28f63
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0x560fcfdded6c - core::fmt::write::h99465148a27e4883
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0x560fcffa87ad - std::io::Write::write_fmt::hee8dfd57bd179ab2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0x560fcffd9a7e - std::sys_common::backtrace::_print::h019a3cee3e814da4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x560fcffd9a7e - std::sys_common::backtrace::print::h55694121c2ddf918
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x560fcffd9663 - std::panicking::default_hook::{{closure}}::h29cbe3da3891b0b0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0x560fcffda629 - std::panicking::default_hook::h881e76b2b8c74280
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0x560fcffda629 - std::panicking::rust_panic_with_hook::hcc36e25b6e33969c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:     0x560fcffda15c - std::panicking::begin_panic_handler::{{closure}}::ha415efb0f69f41f9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
  13:     0x560fcffda0b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h395fe90f99451e4e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x560fcffda0a1 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:     0x560fcfb86ed4 - core::panicking::panic_fmt::h452a83e54ecd764e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:     0x560fcfb87442 - core::result::unwrap_failed::hed0fccbe07e724fc
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
  17:     0x560fcfc375e5 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::hd0f8bbbac1569650
  18:     0x560fcfcac48f - ai00_server::main::had5bd28e0605f84b
  19:     0x560fcfd729f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0e7061c307683ba8
  20:     0x560fcfcabf55 - main
  21:     0x7f772f96d1ca - <unknown>
  22:     0x7f772f96d285 - __libc_start_main
  23:     0x560fcfbbb7b5 - _start
  24:                0x0 - <unknown>
```

**Comment by cryscan** [comment]
Could you make sure that the file `assets/www/index.zip` is not broken?

**Comment by chymian** [comment]
thanks @cryscan , that helped.
since there is __no__ installation how-to, which describes that one hast to clone the repo, it might be a good idea, to write a complete installation guide.
what's written in the readme just don't work.

**Comment by cryscan** [comment]
I see. Actually what missing is setting up git-lfs. Will improve that.
